"""add DetectionResult model

Revision ID: 3517424f56b5
Revises: a928a0a5102b
Create Date: 2026-07-29 01:34:08.672596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3517424f56b5'
down_revision: Union[str, Sequence[str], None] = 'a928a0a5102b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detection_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('attack_probability', sa.Float(), nullable=False),
    sa.Column('is_attack', sa.Boolean(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("risk_level IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')", name='chk_risk_level_valid'),
    sa.CheckConstraint('attack_probability >= 0.0 AND attack_probability <= 1.0', name='chk_probability_range'),
    sa.CheckConstraint('row_index >= 0', name='chk_row_index_positive'),
    sa.ForeignKeyConstraint(['job_id'], ['analysis_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'row_index', name='uq_detection_result_job_row')
    )
    op.create_index('ix_detection_results_is_attack', 'detection_results', ['is_attack'], unique=False)
    op.create_index('ix_detection_results_job_id', 'detection_results', ['job_id'], unique=False)
    op.create_index('ix_detection_results_risk_level', 'detection_results', ['risk_level'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_detection_results_risk_level', table_name='detection_results')
    op.drop_index('ix_detection_results_job_id', table_name='detection_results')
    op.drop_index('ix_detection_results_is_attack', table_name='detection_results')
    op.drop_table('detection_results')
    # ### end Alembic commands ###
